### ISSUE TITLE
[ELWCAMEL] Cross Country Camel - Failed to Load Database error

### ISSUE THREAD

**Issue by robbiew** [mbbsemu/MBBSEmu#374]
**Module Information**
* Identifier [ELWCAMEL]
* Module Name [Cross Country Camel]
* Version [3]

**Describe the bug**
When starting ./MBBSemu after installing the module, an error occurs and mbbsemu exits:

`Critical Exception has occurred:
System.ArgumentException: Failed to load database /home/robbiew/mbbsemu/modules/ELWCAMEL/ELWCAMEL.DAT: Cannot import v6 Btrieve database /home/robbiew/mbbsemu/modules/ELWCAMEL/ELWCAMEL.DAT - only v5 databases are supported for now. Please contact your ISV for a downgraded database.
`

**Software Information:**
- OS: [Ubuntu 20.04]
- Telnet Client [SyncTerm]

**Comment by enusbaum** [comment]
Hey @robbiew -- This is an issue with the module that needs to be addressed by the ISV. They published the WG2 version of the games using BTRIEVE v6 .DAT files, which aren't supported by WG 2.0, and thus not supported by MBBSEmu.

Sorry! 😞

**Comment by robbiew** [comment]
Gotcha, thanks!
