### ISSUE TITLE
[FW_OTHEL] Farwest Othello - Unknown or Unimplemented Imported Library

### ISSUE THREAD

**Issue by robbiew** [mbbsemu/MBBSEmu#375]
**Module Information**
* Identifier [FW_OTHEL]
* Module Name [Farwest Othello 
* Version [5.13]

**Describe the bug**
Starting ./MBBSemu with module installed generates this error and then exits:
`2021-01-20 10:56:25.4142 Error MBBSEmu.HostProcess.MbbsHost.PatchRelocation Unknown or Unimplemented Imported Library: FW_MSG
Critical Exception has occurred:
System.IO.FileNotFoundException: Could not find file '/home/robbiew/mbbsemu/modules/FW_OTHEL/FW_ACT.MCV'.
File name: '/home/robbiew/mbbsemu/modules/FW_OTHEL/FW_ACT.MCV'
`

**Software Information:**
- OS: [Ubuntu 20.04]
- Telnet Client [SyncTerm]

**Comment by robbiew** [comment]
Just to note, this error also happens for me on the other Farwest game, Farwest Trivia FW_FWTRIV.

**Comment by tuday2** [comment]
@robbiew Othello download updated to include .MCV

https://download.mbbsemu.com/modules/FW_OTHEL/FW_OTHEL_MBBSEmu.zip

**Comment by tuday2** [comment]
Still investigating Farwest Trivia issue

**Comment by tuday2** [comment]
@robbiew Here is the corrected Farwest Trivia. 

https://download.mbbsemu.com/modules/FW_FTRIV/FW_FTRIV_MBBSEmu.zip
