### ISSUE TITLE
[RCIROSE] The Rose Council of Guardians - Missing Ordinal

### ISSUE THREAD

**Issue by enusbaum** [mbbsemu/MBBSEmu#390]
**Module Information**
* RCIROSE 
* The Rose Council of Guardians
* v2.00.01

**Describe the bug**
Missing Ordinal during startup/INIT:

`MAJORBBS.866: READ`

**Screenshots**
![image](https://user-images.githubusercontent.com/1139047/106368303-98dd4380-6316-11eb-92fb-43b74407aa5e.png)

**Comment by enusbaum** [comment]
![image](https://user-images.githubusercontent.com/1139047/106368682-8284b700-6319-11eb-9938-d65e4c323a6f.png)

**Comment by tuday2** [comment]
Added in #394
