### ISSUE TITLE
Add text / ascii mode to fopen

### ISSUE THREAD

**Issue by synacktic** [mbbsemu/MBBSEmu#403]
Dear libc guru (@paladine),

The Galacticomm fopen, like the Borland, dos, and others has a text mode for opening files. That needs implementing to fix games like Kyrandia that, at the very least, end up with text formatting foo. 

We already have a flag for text mode, we just need to do something with it.

Primary difference will be removing all carriage returns when reading and converting all linefeeds to carriage return + linefeed on writing. 

The Borland C sample code shows this to be the correct behavior, as do the MS docs, the way Kyrandia was coded, etc.

**Comment by synacktic** [comment]
With my PR merged, this should be all good

**Comment by paladine** [comment]
You can tag an issue in the PR so that when the PR merges, it auto closes. I think you just say something to the effect of "closes #403" and GitHub works its magic
