### ISSUE TITLE
[SFABLX] Blox - Cannot Re-enter module after exiting, requires restart MBBSEmu

### ISSUE THREAD

**Issue by dlightman311** [mbbsemu/MBBSEmu#46]
~~1) Instructions option displays nothing.~~

~~2) Reset high scores option crashes MBBSEmu with missing ordinal 211 (FILELENGTH).~~

~~3) Pressing P to play and not specifying a level (default 0) at the prompt produces a newline and enter has to be pressed again to enter the game. Specifying the level and pressing enter loads the game as normal.~~

~~4) When the demo row limit is reached (10 rows cleared) a box is displayed indicating the demo is over and to press any key to continue. No combination of keys will exit the demo message and nothing is logged. Once this occurs if the same user attempts to re-enter the module after level selection they receive a blank screen. Once MBBSEmu is restarted the user can re-enter.~~

~~5) If the module is played for long enough it eventually hangs and no new pieces are generated nor do the options to redraw screen, quit or pause work. Nothing is logged when this occurs. Experienced this at 67, 85, 88 and 126 bits played in both DEMO and non-DEMO modes. Dropping connection and re-entering the module works.~~

6) If you exit the module menu with X then press X at the main menu but answer no to the logoff question you cannot re-enter Blox until MBBSEmu is restarted. Attempts to enter print the Blox module menu then return you to the main menu. Once this occurs the module is inaccessible for all users.

**Comment by tuday2** [comment]
2. Going to move into it's own issue
4. Is fixed using Build 100920-8

**Comment by robbiew** [comment]
This is happening to me on every game I connect to via Rlogin (via individual port) -- *except* Crossroads of the Elements. Game launches once, but exiting prevents any game (except Crossroads) from launching until restart...

Linux 64
Rlogin via Mystic

**Comment by enusbaum** [comment]
I wonder if we need to cleanup something on User Status/Substate -- I'm not sure we clean that up on exit.

**Comment by enusbaum** [comment]
Looks like we are cleaning it up. 

https://github.com/mbbsemu/MBBSEmu/blob/3791f736f4ca9430fa7133567240525a5f516e95/MBBSEmu/HostProcess/MbbsHost.cs#L511

Something must be getting left over from the previous runs to prevent the re-entry though. Might need to see whats getting set on `SetState()` on the exported module.

**Comment by tuday2** [comment]
Resolved in latest nightly build
