### ISSUE TITLE
User gender is assumed to be male.

### ISSUE THREAD

**Issue by geedubess** [mbbsemu/MBBSEmu#480]
During a nostalgic playthrough of Kyrandia, I realized that you can't proceed past Level 14 without having two differently-gendered accounts logged in: https://www.dragonsworn.net/kyrandia.html#walk. Unfortunately, gender appears to be hard-coded in this emulation.

It would be great if there were a way to set the gender associated with a user account in order to have differently gendered accounts active at the same time.

https://github.com/mbbsemu/MBBSEmu/blob/d6ce36163cbe372a650cbdcc01497ae169172bf2/MBBSEmu/HostProcess/Structs/UserAccount.cs#L383

**Comment by enusbaum** [comment]
So there are two ways we can handle this.

1. Add it to the signup process by adding an additional question for sex/gender during signup
2. Add a command which allows users to modify this on the fly and have it persist when their record is written to `BBSUSR.DAT`

I'm leaning 2 as it's more flexible, but 1 would probably be the easiest. Perhaps both?

**Comment by geedubess** [comment]
I am not invested in the implementation, but (2) does seem more flexible, provided the configuration persists and may be modified from a MBBS connection (vs just the console), and would be helpful if there are existing accounts that need to be modified. The signup process is incredibly brief (username/pass/email), so I'm not sure if it's appropriate to start adding more to is?
