### ISSUE TITLE
[WCCMMUD] Majormud - FSD - Trying to save a character crashes the emulator

### ISSUE THREAD

**Issue by fletcherm** [mbbsemu/MBBSEmu#494]
**Module Information**
* Majormud
* Using the mmud111p zip package

**Describe the bug**

The emulator crashes when using the SAVE button at the bottom of the character editor.

**To Reproduce**

1. Create a new character. Race & class don't matter
2. Work your way down the character editor. Change some stats along the way.
3. Press enter on the SAVE button at the bottom
4. See the emulator crash with this error

```
mbbsemu_1  | Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
mbbsemu_1  |    at MBBSEmu.HostProcess.HostRoutines.FsdRoutines.InFullScreenDisplay(SessionBase session)
mbbsemu_1  |    at MBBSEmu.HostProcess.HostRoutines.FsdRoutines.ProcessSessionState(SessionBase session, Dictionary`2 modules)
mbbsemu_1  |    at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
mbbsemu_1  |    at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
mbbsemu_1  |    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
mbbsemu_1  | --- End of stack trace from previous location ---
mbbsemu_1  |    at System.Threading.ThreadHelper.ThreadStart()
```

**Expected behavior**

The updated character info should be saved. And not crash the emulator along the way :)

**Software Information:**
- OS: Running in mbbsemu-docker image on an Ubuntu host
- Telnet Client Megamud

**Comment by fletcherm** [comment]
@enusbaum Did some more testing with this.

Saving in the Majormud character editor doesn't *crash* anymore, but it prints N/A and everything hangs.

Two steps forward, one step back I guess.

Same OS and telnet client as above.

Screenshot attached.

<img width="855" alt="BBS" src="https://user-images.githubusercontent.com/147532/124813021-5d344e80-df32-11eb-9b47-da12cd008798.png">

**Comment by fletcherm** [comment]
@enusbaum Nothing in the logs either. Let me know if there is anything else I can provide.

**Comment by enusbaum** [comment]
You can't use the character name `sysop`, I know this causes issues.

**Comment by fletcherm** [comment]
Yup, you're right. Changing the name helped. Thanks!
