### ISSUE TITLE
[MBBSEmu] wishlist: handle crashes and SYS SHUTDOWN

### ISSUE THREAD

**Issue by ftoledo** [mbbsemu/MBBSEmu#504]
MBBSEmu should capture module crashes and avoid closing the application completely.

It should have some error counters, leave them in a log but it should keep the application active until it is closed (for example by a /SYS SHUTDOWN command)

**Comment by enusbaum** [comment]
Crash Isolation was implemented in #590 

Now when a module crashes, users are gracefully exited from the module and a crash report is generated.
