### ISSUE TITLE
[WCCMMUD] Majormud - Needs further line wrapping improvements

### ISSUE THREAD

**Issue by fletcherm** [mbbsemu/MBBSEmu#526]
**Module Information**
* WCCMMUD
* Majormud
* mbbsemu-ized 1.11p

**Describe the bug**

@paladine introduced some custom line wrapping code so that Majormud wouldn't print long strings all on one line.

It mostly works and Megamud is happy, but there is at least one place the wrapping isn't quite right.

I'll add screenshots to this as I find these places.

**Expected behavior**
Line wrapping should match worldgroup's.

**Screenshots**

![image](https://user-images.githubusercontent.com/147532/147890446-25e21ce5-6efc-4f93-a902-d6f285d55857.png)

Mbbsemu on the left, wg3 on the right

**Software Information:**
- OS: Ubuntu 20.04
- Megamud

**Comment by paladine** [comment]
There's some indication that the data files have line breaking information in them, see below

```

**Comment by enusbaum** [comment]
@fletcherm This should now be fixed with #529 -- give it another test and let us know!

**Comment by fletcherm** [comment]
Yep, ran through this last night and today. Looks good now. Thanks.
