### ISSUE TITLE
[WCCMMUD] Majormud - `train stats` full screen editor does not return control to the character

### ISSUE THREAD

**Issue by fletcherm** [mbbsemu/MBBSEmu#552]
**Module Information**
* Identifier WCCMMUD
* Module Name Majormud
* Version 1.11p package

**Describe the bug**

There are at least two ways to edit your character's stats with the full screen editor:

1. Initial character creation.
2. Walking into a room with a trainer and using the `train stats` command
3. ... maybe more - perhaps there is something exotic that triggers training... not relevant for this item

Case #1 is working mostly ok (except for the extra line being printed, which is #544). Once training is finished you get control of your character.

Case #2 is causing this issue - after training stats, control never returns to the character. I have been getting control back by forcing Megamud to hangup, reconnect, and re-enter the game.

**To Reproduce**

1. Create a new character and save it with whatever stats. Default is fine. Wait until you get control of your character.
2. Walk `w`, `w`, `n`. This will take you to the Newhaven trainer room.
3. `train stats`
4. Step through the editor again and save.
5. See that control never returns to the player - it looks like it has hung after the SET SUICIDE message.

**Expected behavior**

Control should immediately return to the player.

**Screenshots**

<img width="662" alt="Screen Shot 2022-03-15 at 14 35 57" src="https://user-images.githubusercontent.com/147532/158448011-fa917c82-0231-454b-b4e1-4150d9b9331f.png">

Screenshot of me, patiently waiting.

**Software Information:**
- OS: mbbsemu docker
- Telnet Client: Megamud

**Comment by enusbaum** [comment]
Looked into this with @fletcherm 

The error seemed to be related to the incrementing of `substt` when returning control from the FSD back to the module. `substt` entered with a value of `130` and was being incremented to `131`. 

The result was that the subsequent call to `STTROU` entered a switch statement off `substt`, where value `130` calls `_EXECUTE_INPUT`, and `131` enters a brief branch with `Command Interrupted` error being processed. 

Commenting out the `substt` increment in `FsdRoutines.cs` method `ExitingFullScreenDisplay`. 

The change was introduced here:
https://github.com/mbbsemu/MBBSEmu/commit/95f73bcdce044b6c2e0417d15ac96e5ff47f6f4e#diff-a87ac8064611f7de11b831951571dabd6135f79766b72de80e5f93725dbb2c6a

Commenting out incrementing `substt` appears to fix this issue.

**Comment by fletcherm** [comment]
@enusbaum I believe you said Swords of Chaos is the other module we've had that uses the FSD.

I know 0% about that game beyond its name and that it exists.

Do you know it well enough to test out the FSD in it and confirm the `substt` change does not break it?

**Comment by fletcherm** [comment]
@enusbaum What'd yah wanna do about this one? Time to YOLO the change and hope no other modules complain? ;-)
