### ISSUE TITLE
MBBSEMU - Changes in setup wizard are not reflected in appsettings.json

### ISSUE THREAD

**Issue by Purduecoz** [mbbsemu/MBBSEmu#605]
MBBSEMU Stable Alpha v1.0-alpha-112423

Making changes to the default options in the new MBBSEmu GUI wizard does not reflect the changes made either in the initial setup wizard review or when the appsettings.json file is written.

To reproduce, change simple items such as BBS Title, Registration number, or telnet port

Expected behavior - the options changes are written to appsettings.json

Behavior - the default options are still written

 **Software Information:**
- OS: Windows 11 23H2

**Comment by enusbaum** [comment]
I've seen this issue crop up with the "Self-Contained" EXE files that dotnet packages with not properly reflecting `pwd`

I think I'll add the "file saved to" or perhaps a save dialogue since I _think_ pwd for the packaged EXE is a temp folder, and not the application directory.

**Comment by enusbaum** [comment]
In #606 I added a file dialogue at the end of setup and a message box confirming the path. 

![image](https://github.com/mbbsemu/MBBSEmu/assets/1139047/20222aa6-2d30-4342-a52e-5e971407cdee)
![image](https://github.com/mbbsemu/MBBSEmu/assets/1139047/46db338e-421b-44bf-a042-b622b873d707)

This should help us around the `pwd` issue for now.

**Comment by enusbaum** [comment]
Fixed with #606
